CocukGelisimi_MVC/Controllers/StudentInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CocukGelisimi_MVC.Models.Entity;
using System.IO;


namespace CocukGelisimi_MVC.Controllers
{
    public class StudentInfoController : Controller
    {
        // GET: StudentInfo
        Cocuk_Gelisimi_DbEntities1 db = new Cocuk_Gelisimi_DbEntities1();
        public ActionResult Index()
        {
            // ------------ Öğrencileri Listeleme --------------------
            var values = db.Table_Student.ToList();
            return View(values);
        }

        // ------- bu kısım öğrenci ekle butonuna bastıgımızda boş deger girmemesi için yaptık -----------
        [HttpGet]
        public ActionResult AddStudent() 
        { 
            return View();
        }

        // ------------- bu kısım öğrenci ekle kısmı ------------------------
        [HttpPost]
        public ActionResult AddStudent(Table_Student p)
        {
            if (Request.Files.Count>0)
            {
                //  bu kısım fotoğraf ekleme kısmı 
                string filename = Path.GetFileName(Request.Files[0].FileName);
                string extension = Path.GetExtension(Request.Files[0].FileName);
                string pth = "~/StudentPics/" +filename + extension;
                Request.Files[0].SaveAs(Server.MapPath(pth));
                p.StudentPicture= "/StudentPics/" + filename + extension;
            }
            db.Table_Student.Add(p);
            db.SaveChanges();
            // eger return View ("Index") Kullanırsan hata alırsın. Hata: Model.get null hatası gelir.
            return RedirectToAction("Index");
        }

        // --------------- Öğrncileri silme ---------------------------------
        public ActionResult DeleteStudent(int id)
        {
            var student = db.Table_Student.Find(id);
            db.Table_Student.Remove(student);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        
        // ------------------- Öğrecileri StudentId ye göre Guncelleme SAyfasına Aktarma --------------

        public ActionResult GetStudentInfo(int id)
        {
            var getstdnt = db.Table_Student.Find(id);
            return View("GetStudentInfo", getstdnt);

        }
        // ------------------Guncelleme Sayfasında Öğrenci Guncelleme --------------------------
        public ActionResult UpdateStudent(Table_Student p2)
        {
            if (Request.Files.Count > 0)
            {
                // bu kısım fotoğraf ekleme kısmı
                string filename = Path.GetFileName(Request.Files[0].FileName);
                string extension = Path.GetExtension(Request.Files[0].FileName);
                string pth = "~/StudentPics/" + filename + extension;
                Request.Files[0].SaveAs(Server.MapPath(pth));
                p2.StudentPicture = "/StudentPics/" + filename + extension;
            }
            var updateStudent = db.Table_Student.Find(p2.StudentID);
            updateStudent.StudentID = p2.StudentID;
            updateStudent.StudentFirstName = p2.StudentFirstName;
            updateStudent.StudentLastName = p2.StudentLastName;
            updateStudent.StudentYearAsMonth = p2.StudentYearAsMonth;
            if(!string.IsNullOrEmpty(p2.StudentPicture))
                updateStudent.StudentPicture = p2.StudentPicture;
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        // ------------- Öğrenci listesini çıktı şeklinde alma ----------------------

        public ActionResult StudentlistOutput()
        {
            var values = db.Table_Student.ToList();
            return View(values);
        }
    }
}

CocukGelisimi_MVC/Views/StudentInfo/AddStudent.cshtml
@model CocukGelisimi_MVC.Models.Entity.Table_Student
@{
    ViewBag.Title = "AddStudent";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card" id="cardAddStudent" style="width: 600px; height: 500px; border-radius: 3px; margin: 15px; box-shadow: 10px 10px 1px rgba(0,0,0,.2); ">
    <div class="card-header">
        ÖĞRENCİ EKLEME PANELİ
    </div>
    <div class="card-body">
        @using (Html.BeginForm("AddStudent", "StudentInfo", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <label class="mt-2">Öğrenci ID</label>
            @Html.TextBoxFor(m => m.StudentID, new { @class = "form-control" })
            <label class="mt-2">Öğrenci Ad</label>
            @Html.TextBoxFor(m => m.StudentFirstName, new { @class = "form-control" })
            <label class="mt-2">Öğrenci Soyad</label>
            @Html.TextBoxFor(m => m.StudentLastName, new { @class = "form-control" })
            <label class="mt-2">Öğrenci Yaş(Ay Olarak)</label>
            @Html.TextBoxFor(m => m.StudentYearAsMonth, new { @class = "form-control" })
            <label class="mt-2">Öğrenci Fotoğraf</label>
            <input type="file" name="StudentPicture" class="form-control" />
            <div class="d-flex justify-content-between col-12 mt-4">
                <div class="col-2 ">
                    <button class="btn btn-success" type="submit">Ekle</button>
                </div>

            </div>
        }
    </div>

</div>

CocukGelisimi_MVC/Views/StudentInfo/GetStudentInfo.cshtml
@model CocukGelisimi_MVC.Models.Entity.Table_Student
@{
    ViewBag.Title = "GetStudentInfo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card" style="width: 600px; height: 500px; border-radius: 3px; margin: 15px; box-shadow: 10px 10px 1px rgba(0,0,0,.2); ">
    <div class="card-header">
        ÖĞRENCİ GÜNCELLEME PANELİ
    </div>
    <div class="card-body">
        @using (Html.BeginForm("UpdateStudent", "StudentInfo", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(m=>m.StudentID) // bu kısmı ekledik ki guncellede null değer  gelmesin hata vermesin
            <label class="mt-2">Öğrenci ID</label>
            @Html.TextBoxFor(m => m.StudentID, new { @class = "form-control" })
            <label class="mt-2">Öğrenci Ad</label>
            @Html.TextBoxFor(m => m.StudentFirstName, new { @class = "form-control" })
            <label class="mt-2">Öğrenci Soyad</label>
            @Html.TextBoxFor(m => m.StudentLastName, new { @class = "form-control" })
            <label class="mt-2">Öğrenci Yaş(Ay Olarak)</label>
            @Html.TextBoxFor(m => m.StudentYearAsMonth, new { @class = "form-control" })
            <label class="mt-2">Öğrenci Fotoğraf</label>
            <input type="file" name="StudentPicture" class="form-control" />
            <div class="d-flex justify-content-between col-12 mt-4">
                <div class="col-2 ">
                    <button class="btn btn-success" type="submit">Güncelle</button>
                </div>

            </div>
        }
    </div>

</div>

CocukGelisimi_MVC/Views/StudentInfo/Index.cshtml
@using CocukGelisimi_MVC.Models.Entity

@model List<Table_Student>



@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="table-responsive">
            <table class="table caption-top table-hover align-middle">
                <caption><strong>ÖĞRENCİ LİSTESİ</strong></caption>
                <thead class="table-dark">
                    <tr>
                        <th>Öğrenci No</th>
                        <th>Öğrenci Ad</th>
                        <th>Öğrenci Soyad</th>
                        <th>Öğrenci Yaş(Ay)</th>
                        <th>Öğrenci Fotoğraf</th>
                        <th>Düzenle</th>
                    </tr>
                </thead>
                <tbody class="table-group-divider">

                    @foreach (var stdnt in Model)
                    {
                        <tr>
                            <td>@stdnt.StudentID</td>
                            <td>@stdnt.StudentFirstName</td>
                            <td>@stdnt.StudentLastName</td>
                            <td>@stdnt.StudentYearAsMonth</td>
                            <td><img src="@stdnt.StudentPicture" width="100" height="100" /></td>
                            <td>

                                <a href="/StudentInfo/DeleteStudent/@stdnt.StudentID" id="iconDeleteStudent" onclick="return confirm('Silme İşlemine Devam Etmek İstiyor Musunuz?')"><span class="text-danger"><i class="fa-solid fa-trash"></i></span></a>
                                <a href="/StudentInfo/GetStudentInfo/@stdnt.StudentID"><span class="text-primary ms-2"><i class="bi bi-pencil-square"></i></span></a>
                            </td>
                        </tr>

                    }
                </tbody>
            </table>

            <div class="container my-2">
                <div class="row">
                    <a href="/StudentInfo/AddStudent" class="btn btn-success">Öğrenci Ekle</a>
                </div>

            </div>
        </div>
    </div>
</div>
@*----------------------------------------------------------------------------------
    <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#Modal1">Öğrenci Ekle</button>
    <div class="modal" id="Modal1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title">Öğrenci Ekleme Paneli</h3>
                </div>
                <form method="post" action="/StudentInfo/AddStudent">
                @using (Html.BeginForm("AddStudent", "StudentInfo", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                    <div class="modal-body">
                        <label>Öğrenci Numarası</label>
                        <input type="text" name="StudentID" class="form-control" />

                        <label>Öğrenci Adı</label>
                        <input type="text" name="StudentFirstName" class="form-control" />

                        <label>Öğrenci Soyadı</label>
                        <input type="text" name="StudentLastName" class="form-control" />

                        <label>Öğrenci Yaş(Ay Olarak)</label>
                        <input type="text" name="StudentYearAsMonth" class="form-control" />

                        <label>Öğrenci Fotoğrafı</label>
                        <input type="file" name="StudentPicture" class="form-control" />
                    </div>
                    <div class="modal-footer">
                        <div class="d-flex justify-content-between col-12">
                            <div class="col-2 ">
                                <button class="btn btn-success" type="submit">Ekle</button>
                            </div>
                            <div class="col-2 ">
                                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Vazgeç</button>
                            </div>
                        </div>
                    </div>
                 }
                </form>
            </div>
        </div>
    </div>*@

CocukGelisimi_MVC/Views/StudentInfo/StudentlistOutput.cshtml
@using CocukGelisimi_MVC.Models.Entity

@model List<Table_Student>


@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    @*------font awesome ıcons------*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    @*------fbootstrap ıcons------*@
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

    @*------all bootstrap------*@
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    @*------my stylesheet------*@
    <link href="~/StyleSheet1.css" rel="stylesheet" />

    @*------links for table (css)------*@
    <link href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/buttons/2.3.6/css/buttons.dataTables.min.css" rel="stylesheet">




    <title>StudentlistOutput</title>
</head>
<body>
    <div>
        <div class="container">
            <div class="row">
                <div class="table-responsive table-bordered mt-3">
                    <table class="table caption-top" id="tblStudentlist">
                        <caption><strong>ÖĞRENCİ LİSTESİ</strong></caption>
                        <thead class="tableheadStudentlistOutput" style="background-color:#706565">
                            <tr>
                                <th>Öğrenci No</th>
                                <th>Öğrenci Ad</th>
                                <th>Öğrenci Soyad</th>
                                <th>Öğrenci Yaş(Ay)</th>
                                <th>Öğrenci Fotoğraf</th>

                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var stdnt in Model)
                            {
                                <tr>
                                    <td>@stdnt.StudentID</td>
                                    <td>@stdnt.StudentFirstName</td>
                                    <td>@stdnt.StudentLastName</td>
                                    <td>@stdnt.StudentYearAsMonth</td>
                                    <td><img src="@stdnt.StudentPicture" width="100" height="100" /></td>

                                </tr>

                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>





    @*------Scripts for tables and buttons------*@
    <script src="~/Scripts/jquery-3.7.0.min.js"></script>
    <script src="~/DataTableScripts/jquery.dataTables.min.js"></script>
    <script src="~/DataTableScripts/dataTables.buttons.min.js"></script>
    <script src="~/DataTableScripts/jszip.min.js"></script>
    <script src="~/DataTableScripts/pdfmake.min.js"></script>
    <script src="~/DataTableScripts/vfs_fonts.js"></script>
    <script src="~/DataTableScripts/buttons.html5.min.js"></script>
    <script src="~/DataTableScripts/buttons.print.min.js"></script>


    @*------JavaScript Codes for Table------*@
    <script>
        $(document).ready(function () {
            $('#tblStudentlist').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'copy', 'csv', 'excel', 'pdf', 'print'
                ]
            });
        });
    </script>


















    @*<script src="~/Popper/popper.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>*@

    @*<script>
            $(document).ready(function () {
                var table = $('#tblStudentlist').DataTable({
                    lengthChange: false,
                    buttons: ['copy', 'csv', 'excel', 'pdf', 'print']
                });

                table.buttons().continer()
                appendTo('#tblStudentlist .col-md-6:eq(0)');
            });
        </script>*@
</body>
</html>